# Generated by Django 4.2.29 on 2026-03-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Job major',
                'verbose_name_plural': 'Job majors',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, help_text='Two-letter US state code (e.g. CA, NY). Leave blank for remote-only roles.', max_length=2)),
                ('is_remote', models.BooleanField(default=False)),
                ('employment_type', models.CharField(choices=[('internship', 'Internship'), ('full_time', 'Full-time'), ('part_time', 'Part-time')], default='internship', max_length=20)),
                ('url', models.URLField(help_text='Link to the external job posting or application page.', max_length=500)),
                ('description', models.TextField(help_text='Short, student-friendly summary shown in the listings.')),
                ('posted_at', models.DateField(blank=True, help_text='Optional posted date for display and ordering.', null=True)),
                ('source', models.CharField(blank=True, help_text="Optional source label (e.g. 'Company career site', 'Example data').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this job from the public listings without deleting it.')),
                ('majors', models.ManyToManyField(help_text='Which majors is this role most relevant for?', related_name='jobs', to='jobs.jobmajor')),
            ],
            options={
                'ordering': ['-posted_at', '-created_at'],
            },
        ),
    ]
