# Generated by Django 5.2.13 on 2026-04-16 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('weight', models.FloatField(default=1.0, help_text='Scoring multiplier for this question (1.0, 1.5, or 2.0).')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique option key submitted by the frontend (e.g. q1a).', max_length=16)),
                ('label', models.CharField(default='A', help_text='Display label: A, B, C, or D.', max_length=1)),
                ('text', models.CharField(max_length=255)),
                ('archetype', models.ForeignKey(blank=True, help_text='The single archetype this choice awards points to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices', to='careers.personalitytype')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question')),
            ],
            options={
                'ordering': ['question', 'key'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text='Raw submitted answers: {question_order: choice_key}.')),
                ('scores', models.JSONField(default=dict, help_text="Final archetype scores: {'systems_thinker': 8.5, ...}.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_results_primary', to='careers.personalitytype')),
                ('secondary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_results_secondary', to='careers.personalitytype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
