# Generated by Django 5.2.13 on 2026-04-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='archetype',
        ),
        migrations.AddField(
            model_name='choice',
            name='weights',
            field=models.JSONField(default=dict, help_text='Per-archetype scoring weights for this choice. E.g. {"systems_thinker": 1.0, "analytical_solver": 0.4, ...}'),
        ),
    ]
