# Generated by Django 6.0.2 on 2026-03-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_profile_and_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_toggles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='base_style',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('friendly', 'Friendly'), ('professional', 'Professional'), ('concise', 'Concise'), ('detailed', 'Detailed')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_instructions',
            field=models.TextField(blank=True, help_text='How you want the AI to respond (e.g. tone, style).'),
        ),
    ]
