# Generated by Django 4.2.29 on 2026-03-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_avatar_bio_personalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Checked when the user has clicked their verification link. Unchecked means they can still log in, but some features may be limited.'),
        ),
    ]
