from datetime import date


EXAMPLE_JOBS = [
    {
        "title": "Software Engineering Intern",
        "company": "BrightPath Labs",
        "city": "Seattle",
        "state": "WA",
        "is_remote": True,
        "employment_type": "internship",
        "majors": ["computer_science", "engineering"],
        "url": "https://example.com/jobs/brightpath-software-intern",
        "description": "Work with a small engineering team building internal tools in Python and JavaScript. Great for CS majors who want real-world experience.",
        "posted_at": date(2026, 3, 1),
        "source": "Example data",
    },
    {
        "title": "Marketing & Analytics Intern",
        "company": "Northbridge Consulting",
        "city": "Chicago",
        "state": "IL",
        "is_remote": False,
        "employment_type": "internship",
        "majors": ["business", "communications"],
        "url": "https://example.com/jobs/northbridge-marketing-intern",
        "description": "Help build and analyze campaigns for education and nonprofit clients. Mix of data analysis and content work.",
        "posted_at": date(2026, 2, 20),
        "source": "Example data",
    },
    {
        "title": "Junior Data Analyst",
        "company": "Summit Health Network",
        "city": "Atlanta",
        "state": "GA",
        "is_remote": True,
        "employment_type": "full_time",
        "majors": ["health_sciences", "social_sciences", "business"],
        "url": "https://example.com/jobs/summit-data-analyst",
        "description": "Full-time role cleaning, analyzing, and visualizing healthcare operations data. SQL and Excel required; Python a plus.",
        "posted_at": date(2026, 2, 5),
        "source": "Example data",
    },
    {
        "title": "Environmental Field Technician (Summer)",
        "company": "GreenRiver Environmental",
        "city": "Denver",
        "state": "CO",
        "is_remote": False,
        "employment_type": "internship",
        "majors": ["environmental", "agriculture"],
        "url": "https://example.com/jobs/greenriver-field-tech",
        "description": "Summer fieldwork role assisting with water quality sampling and habitat surveys across Colorado.",
        "posted_at": date(2026, 1, 28),
        "source": "Example data",
    },
    {
        "title": "Resident Assistant (RA)",
        "company": "Campus Housing, Example University",
        "city": "Austin",
        "state": "TX",
        "is_remote": False,
        "employment_type": "part_time",
        "majors": ["education", "social_sciences", "humanities"],
        "url": "https://example.com/jobs/exampleu-ra",
        "description": "On-campus student leadership role supporting a residence hall community and planning events.",
        "posted_at": date(2026, 2, 10),
        "source": "Example data",
    },
]

