# Generated by Django 5.2.13 on 2026-04-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('traits', models.JSONField(blank=True, default=list, help_text="List of trait strings, e.g. ['analytical', 'methodical'].")),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('career_direction', models.TextField(blank=True, help_text='Short prose on the career direction for this archetype.')),
                ('strengths', models.TextField(blank=True)),
                ('growth_areas', models.TextField(blank=True, help_text='Subtle growth areas (not weaknesses).')),
                ('identity_statement', models.TextField(blank=True, help_text='First-person identity statement used in results.')),
                ('behavioral_explanation', models.TextField(blank=True, help_text='Paragraph explaining thinking style.')),
                ('why_this_fits', models.TextField(blank=True, help_text='Paragraph on why this archetype fits the user.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('personality_types', models.ManyToManyField(blank=True, related_name='majors', to='careers.personalitytype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('learn_more', models.TextField(blank=True)),
                ('majors', models.ManyToManyField(blank=True, related_name='jobs', to='careers.major')),
                ('primary_archetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='careers.personalitytype')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
